### PR TITLE
Fix WiFi power issues

### PR DESCRIPTION
**Pull request by ConnorRigby**
add some prop files and configurition for those files to fix the brcm chip not starting on some devices.

### CODE REVIEW

**Comment by fhunleth** [comment]
Looks good, I think. Could you squash the commits together?

Also, am I understanding this correctly that there are at least two wifi chips being shipped on RPi3's? I haven't used my RPi3 recently, but it certainly was convincing that wifi worked for me back when I used it. I'm curious how it broke. (Fwiw, I'm still going to merge this even if you don't know.)

**Comment by ConnorRigby** [comment]
As far as i know there is only one chip but i think they might have different firmwares? that is just a theory, i have really no idea why it works. But i have two different Raspberry Pi3's and one works with or with out this fix, and one does not, and Ive gave the file to a couple people in slack and it seems to work for them too. 
Will squash soon. On mobile right now.

**Comment by ConnorRigby** [comment]
There we go squashed together.

**Comment by fhunleth** [comment]
Thanks again for fixing this!!

**Comment by GregMefford** [comment]
@ConnorRigby Thanks for fixing this! I'm curious where you got the firmware and configuration files from. Are they from somewhere in https://github.com/raspberrypi?

**Comment by ConnorRigby** [comment]
@GregMefford I actually stumbled upon the fix in a Buildroot mailing list archive. I can't seem to find it again, but the files themselves came from the OpenElec project. Which presumably came from upstream RPI.

**Pull request merged**
