### PR TITLE
Add support for the Raspberry Pi CM3

### PR DESCRIPTION
**Pull request by fhunleth**

### CODE REVIEW

**Comment by fhunleth** [comment]
I don't have a CM3. If anyone does, let me know if you're able to try this out. I can also get you a `.fw` to make it easier if you'd like.

**Comment by hsztul** [comment]
Hey @fhunleth. I have one at my office. I'll try it out tomorrow when I'm back at my desk and get back to you!

**Comment by hsztul** [comment]
i guess one thing i can't tell from this issue, will the build target will be `rpi3` still or something else like `cm3`?

**Comment by GregMefford** [comment]
It would still be `rpi3` once this PR gets merged and released in a future `nerves_system_rpi3` release. If you want to test it in the meantime, you'd need to tweak your `mix.exs` to point to this `cm3` branch:

```elixir
{:nerves_system_rpi3, github: "nerves-project/nerves_system_rpi3", branch: "cm3"}
```

...and you'd also have to wait for it to compile the system for you, so you should probably take up Frank on his offer to send a `.fw` file, which would be way faster. 😉

**Comment by dylanfareed** [comment]
Thanks @GregMefford and @fhunleth! I'm compiling this locally to test on our CM3s. In parallel I'll ping Frank on slack to see about getting that `.fw` ... 🕐 

Stoked and again thanks for your efforts!

**Comment by mobileoverlord** [comment]
The systems was build and verified by CircleCI. If you don't want to wait, you can download the products from the build artifacts.
https://110-55319430-gh.circle-artifacts.com/0/system/nerves_system_rpi3-e15a18cc4054e804f397ccce44388e8a26072705.fw
https://110-55319430-gh.circle-artifacts.com/0/system/nerves_system_rpi3-e15a18cc4054e804f397ccce44388e8a26072705.tar.gz

But, compiling locally and waiting a little while also works :)

**Comment by fhunleth** [comment]
Merged since it boots!

**Comment by dylanfareed** [comment]
image

Thanks @fhunleth @mobileoverlord @GregMefford

**Pull request merged**
