### PR TITLE
Add nerves_initramfs for auto-revert

### PR DESCRIPTION
**Pull request by jjcarstens**
Initial concept for supporting auto-reverts on rpi systems by booting `initramfs` and using `nerves_initramfs` for checking some uboot env variables to decide if a revert needs to happen.

:warning: For any newcomers, you can ignore the discussion before [this comment](#issuecomment-657743578)

~~There is a chance that `fwup.conf` needs to be adjusted to correctly size boot partition to fit `nerves_initramfs` in by changing Line 73 to:~~

~~If so, that's a breaking change. But if not, we can get away without breaking things 🎉 - I'll be doing more testing in the AM, but wanted to get this up for discussion first.~~

~~If we like this, I'll apply to all the other `rpi` systems as well and sweep documentation.~~

~~Will want nerves-project/nerves_runtime#180 for this~~

### CODE REVIEW

**Comment by fhunleth** [comment]
Great work on putting this together!

I don't see any breaking changes in the `fwup.conf` partition layout. 

The only breaking change I see is that this system will require the `nerves_runtime` release that validates firmware images. We can specify the dependency right now in the `mix.exs`, so rolling this out will require some thought.

**Comment by jjcarstens** [comment]
Looks like this is a breaking change - I did some more testing burning a fw to SD created from the current `nerves_system_rpi3 1.11.1`. Then created a new fw from this PR and can't seem to update with `./upload.sh` script. So something about it is a little too different and still trying to dig into what that is:
```
jonjon@bender:~/repos/playground$ ./upload.sh 
Path: ./_build/rpi3_dev/nerves/images/playground.fw
Product: playground 0.1.0
UUID: 67aa3bd9-134c-5f3b-d1a5-827cd8de4144
Platform: rpi3

Uploading to playground.local...
Running fwup...
fwup: Please check the media being upgraded. It doesn't look like either the A or B partitions are active.
```

**Comment by jjcarstens** [comment]
So I figured out the issue that was "breaking" and turns out it was because this requires `nerves_fw_validated` to be set in order to update, but that isn't set on existing rpi systems.

This can technically happen without a major version bump but would require a user to run `Nerves.Runtime.validate_firmware()` on running systems before updating.

However, after some offline discussion with @fhunleth, we decided to go ahead and scope this under a major version bump because it a decent change to the fs by relying on nerves_initramfs.

So I created a v2.0 branch from main and this is now based off of that. We'll work from there and create release candidates until we feel like everything is in a solid state.

**Comment by jjcarstens** [comment]
@fhunleth This is ready for another review

**Pull request merged**
