### PR TITLE
Enable pstore

### PR DESCRIPTION
**Pull request by ConnorRigby**
I have no idea if this is correct. I was able to mount the pstore, but i wasn't sure how to test it.

Also not exactly sure about this, but my rpi3 was _super_ hot for some reason.

### CODE REVIEW

**Comment by fhunleth** [comment]
This looks pretty close. I'm not sure about the address, 0x0b000000. I put mine at the end of DRAM, but I don't have any reason to believe that 0x0b000000 is a bad address either.

To test, you'll need to mount it: `mount -t pstore pstore /sys/fs/pstore`. That's where everything interesting ends up.

You can put things in there for the next boot a few ways:

1. `File.write("/dev/pmsg0", "hello, world")` - This is where logs would go.
2. Trigger the watchdog: `:heart.set_cmd("attack")`
3. Cause a kernel panic

On the next boot, mount the `pstore` file system (for convenience, mount it in `erlinit.conf`) and start cat'ing the files in that directory.

Before you do any of that, I'd try to figure out why your rpi3 was super hot. That does not sound good.

**Comment by ConnorRigby** [comment]
>  I'm not sure about the address, 0x0b000000. I put mine at the end of DRAM
I copy-pasta that address. It can certainly be moved.

> Before you do any of that, I'd try to figure out why your rpi3 was super hot
I actually have no idea what this is. The PI is underpowered by my PC usb port. 
I'm going to try a different firmware to make sure its not just the pi/setup

**Comment by ConnorRigby** [comment]
a brand new rpi firmware also got pretty hot. Gonna dig up a new pi

**Comment by fhunleth** [comment]
I updated this PR so that it would be consistent with the rpi0. I haven't tested it.

**Pull request merged**
