### PR TITLE
Add block-count size for app part.

### PR DESCRIPTION
**Pull request by elcritch**
It would be nice to be able to set a custom app/data partition size without making a custom `fwup.conf`. Is this doable? Not sure how/if the value will be appropriately converted to an integer.

### CODE REVIEW

**Comment by fhunleth** [comment]
Is the desire for the app partition to go to the end of storage (whatever that is)? If that's what you want, the `expand=true` setting will do that for you in the MBR. The `expand=true` feature hasn't been in `fwup` for long. I was waiting a bit before adding that to the Nerves systems so that there'd be time for it to makes its way through package management. It's in Homebrew and Alpine, but I'm not sure it's made it much further if you're running something else.

**Comment by elcritch** [comment]
Why, yes! I need to store a lot of time series data and want the app partition to grow to whichever SD card it's using. The `expand=true` would be handy. Were you planning on adding it to the default nerves system images once the packages have updated? It's easier to not need to maintain a custom `fwup.conf` just for a custom data partition size.

**Comment by fhunleth** [comment]
Yes, making it the default was the plan.

If you have `fwup v1.3.0` on your dev machine, you can use it right now. It only affects the MBR view of the partition size, so if you're working with an already formatted partition, you'll need to use `resize2fs` or similar or reformat.

**Comment by elcritch** [comment]
Ok thanks, I'll try that out.

**Pull request closed without merging**
