### PR TITLE
Fix regression of sound hardware not working

### PR DESCRIPTION
**Pull request by ConnorRigby**
I'm not 100% happy with this, but it was the only thing i could find to fix it. I'd also be happy to just add this to docs and not have it in the system, but tell users how to do it maybe?

### CODE REVIEW

**Comment by fhunleth** [comment]
The `PA_ALSA_PLUGHW` environment variable isn't used anywhere in the system (I searched the system build tree), so how does this even work?

**Comment by ConnorRigby** [comment]
to be completely honest, i found a thread that said exporting that variable will make alsa work, so i exported it and it worked. i tested with `espeak` and `aplay`.

**Comment by ConnorRigby** [comment]
oh looking further, this basically just sets which device to use, so it's possible that this could/should be done with a configuration file of some sort.

**Comment by fhunleth** [comment]
I still don't understand how this works. `PA` makes this sound like it's a PortAudio thing. None of the official Nerves systems use PortAudio.

**Comment by fhunleth** [comment]
Closing, but please reopen if you have any more information.

**Pull request closed without merging**
